Lanngkah Pertama : Import Library Numpy dan Pandas


In [1]:
import pandas as pd
import numpy as np

In [2]:
# Membaca file CSV dan menampilkan 5 data teratas
df = pd.read_csv("Property Listing Dataset.csv")
df.head()

Location         Price Rooms  Bathrooms  Car Parks  \
0               KLCC, Kuala Lumpur  RM 1,250,000   2+1        3.0        2.0   
1  Damansara Heights, Kuala Lumpur  RM 6,800,000     6        7.0        NaN   
2            Dutamas, Kuala Lumpur  RM 1,030,000     3        4.0        2.0   
3             Cheras, Kuala Lumpur           NaN   NaN        NaN        2.0   
4        Bukit Jalil, Kuala Lumpur    RM 900,000     5        3.0        4.0   

          Property Type Property Character        Size        Furnishing  
0    Serviced Residence         Built-up :  1,335 sqft   Fully Furnished  
1              Bungalow          Land area   6900 sqft  Partly Furnished  
2  Condominium (Corner)         Built-up :  1,875 sqft  Partly Furnished  
3                   NaN                NaN         NaN               NaN  
4  Condominium (Corner)         Built-up :  1,513 sqft  Partly Furnished

Langkah Kedua : Cek values tiap kolom, dan kolom yabg kosong di isi dengan N/A

In [3]:
# Mencari value null/kosong tiap kolom dan menjumlahkannya pada tiap kolom
jml_null = df.isnull().sum()
jml_null

Location                 0
Price                   36
Rooms                  135
Bathrooms              158
Car Parks             1472
Property Type           25
Property Character     110
Size                   110
Furnishing             586
dtype: int64

In [4]:
# Mengganti value kosong dengan nilai 'N/A'
df = df.fillna('N/A')
df.head()

Location         Price Rooms Bathrooms Car Parks  \
0               KLCC, Kuala Lumpur  RM 1,250,000   2+1       3.0       2.0   
1  Damansara Heights, Kuala Lumpur  RM 6,800,000     6       7.0       N/A   
2            Dutamas, Kuala Lumpur  RM 1,030,000     3       4.0       2.0   
3             Cheras, Kuala Lumpur           N/A   N/A       N/A       2.0   
4        Bukit Jalil, Kuala Lumpur    RM 900,000     5       3.0       4.0   

          Property Type Property Character        Size        Furnishing  
0    Serviced Residence         Built-up :  1,335 sqft   Fully Furnished  
1              Bungalow          Land area   6900 sqft  Partly Furnished  
2  Condominium (Corner)         Built-up :  1,875 sqft  Partly Furnished  
3                   N/A                N/A         N/A               N/A  
4  Condominium (Corner)         Built-up :  1,513 sqft  Partly Furnished

In [5]:
# Sudah Tidak ada value kosong dala setiap kolom
df.isnull().sum()

Location              0
Price                 0
Rooms                 0
Bathrooms             0
Car Parks             0
Property Type         0
Property Character    0
Size                  0
Furnishing            0
dtype: int64

Langkah Ketiga : Melakukan Check terhadap Duplikat data dan menghapus salah satunya

In [6]:
# Menghitung jumlah data duplikat
duplikat = df.duplicated().sum()
print(f'Jumlah data duplikat(sebelum dihapus) : {duplikat}')




Jumlah data duplikat(sebelum dihapus) : 68


In [7]:
# Menghapus data duplikat
df = df.drop_duplicates()
print(f'Jumlah data duplikat(sebelum dihapus) : {df.duplicated().sum()}')


Jumlah data duplikat(sebelum dihapus) : 0


Langkah Ketiga : Pastikan value pada kolom 'Rooms', 'Bathrooms', 'Car Parks' Harus menggunakan tipe data number, jika ada value yang tidak menggunakan tipe data number maka di hapus

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4932 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Location            4932 non-null   object
 1   Price               4932 non-null   object
 2   Rooms               4932 non-null   object
 3   Bathrooms           4932 non-null   object
 4   Car Parks           4932 non-null   object
 5   Property Type       4932 non-null   object
 6   Property Character  4932 non-null   object
 7   Size                4932 non-null   object
 8   Furnishing          4932 non-null   object
dtypes: object(9)
memory usage: 385.3+ KB


In [9]:
# Menampilkan nilai unik pada kolom 'Rooms'
df['Rooms'].unique()


array(['2+1', '6', '3', 'N/A', '5', '4', '7', '1', '2', '8', 'Studio',
       '14', '12', '5+1', '9', '13', '20', '3+1', '10'], dtype=object)

In [10]:
# Membersihkan nilai-nilai non-angka
df['Rooms'] = df['Rooms'].str.replace('2\+1|N/A|Studio|5\+1|3\+1', '')

# Mengonversi ke tipe data integer
df['Rooms'] = pd.to_numeric(df['Rooms'], errors='coerce')

# Mengatasi nilai-nilai yang tidak dapat dikonversi menjadi integer
df['Rooms'] = df['Rooms'].fillna(0).astype(int)









<ipython-input-10-e5879b7edba7>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Rooms'] = df['Rooms'].str.replace('2\+1|N/A|Studio|5\+1|3\+1', '')


In [11]:
df['Rooms'].unique()

array([ 0,  6,  3,  5,  4,  7,  1,  2,  8, 14, 12,  9, 13, 20, 10])

In [12]:
# Menampilkan nilai unik pada kolom 'Bathrooms'
df['Bathrooms'].unique()

array([3.0, 7.0, 4.0, 'N/A', 5.0, 2.0, 6.0, 1.0, 9.0, 8.0, 16.0, 12.0,
       11.0, 13.0, 20.0, 10.0], dtype=object)

In [13]:


# Mengganti 'N/A' dengan NaN
df['Bathrooms'] = df['Bathrooms'].replace('N/A', np.nan)

# Mengonversi ke tipe data integer
df['Bathrooms'] = df['Bathrooms'].astype(float)



In [14]:
df['Bathrooms'].unique()


array([ 3.,  7.,  4., nan,  5.,  2.,  6.,  1.,  9.,  8., 16., 12., 11.,
       13., 20., 10.])

In [15]:
# Menampilkan nilai unik pada kolom 'Car parks'
df['Car Parks'].unique()

array([2.0, 'N/A', 4.0, 3.0, 1.0, 5.0, 6.0, 7.0, 10.0, 9.0, 8.0, 13.0,
       12.0, 15.0, 28.0], dtype=object)

In [19]:
# Mengganti string kosong dengan NaN
df['Car Parks'] = df['Car Parks'].replace('', np.nan)

# Mengonversi ke tipe data float
df['Car Parks'] = df['Car Parks'].astype(float)

In [20]:
df['Car Parks'].unique()

array([ 2., nan,  4.,  3.,  1.,  5.,  6.,  7., 10.,  9.,  8., 13., 12.,
       15., 28.])

In [ ]:
df.head(10)